services:
- docker
script:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- make alpine
after_success:
- make push-alpine
notifications:
  email:
    on_success: change
    on_failure: always
env:
  global:
    secure: tCcSfw+iTuurwh4I+V7I+Lzxc4F2dFUXHOpg/VyGk68waEqA1TPl/xmnYL4/lpyKvNUpX2Ks0DwloSMUxeUTYHGefYVROprqcwpv1mAU6Dc7oHoWjfkc0Hhe8xOroJFgbM/UlEC1UdPfHGp3xMXk+cRZgWV+wjFrgeOKSEOLsk0lSDmrYHShnm38FRCuW58319+XhLF7g2h65rshq6EedoGrV9pleVG/O/w1XmEYMFdnn0xrzDZ9zZvsbQ/+gua3MMD84e89xqfjyGQ1ekGY3b/fx2W+IfFgheTskrzvwjwo4Gh7coalxHXyzqvrAkzsSZlVV6C3GWxMGS04LuETCLd9eyLnnZ9RVuiaghR3RPdTZKe/ZPHzIyDR1QJMt+MEgsGIbKsKVKSK+jE0/622MQElaEHgBL9Nb/GPAAPLVxXH3QC7bgq5QhPyCs+XGYurgjr+VBEcACPrPCETnb2kbFwu+F+Dhyv1sFxI9/AG/J/I+mTEj2ZJ2mPxxIhjdqwiIiYsvCX/8TCWV9lEN/MFydMEmHWRNczBOTjQxiOvkYjKpGxT5KpQVt3oywuygI73tiAZkmhw/6krJfxyBWtysaPERIF2IA/hH4aHkDxxz2NgtCqcuFJfPCakwFo88VgoNpRQikU8hXl/4xA6wBg7Im6AAATQu9jwd+TaVl3CCLk=
